//
//  GradeWords.swift
//  WordPositive
//
//  Created by Nathaniel Brown on 9/18/21.
//

import Foundation

struct GradeWords {
  static var first = ["annoy", "ignore", "prefer", "attention", "instead", "problem", "calm", "investigate", "protect", "comfortable", "invite", "proud", "consequences", "important", "question", "curious", "jealous", "reminds", "curve", "leader", "repeat", "decide", "list", "report", "directions", "listen", "rhyme", "discover", "lovely", "respect", "disappointed", "measuring", "searching", "embarrassed", "miserable", "special", "enormous", "mumble", "spotless", "exhausted", "negative", "squirm", "explore", "nervous", "stomped", "fair", "nibbled", "suddenly", "fascinating", "note", "suggestion", "feast", "notice", "surprise", "focus", "observing", "uncomfortable", "frustrated", "opposite", "warning", "gigantic", "ordinary", "wonder", "grumpy", "positive", "worried", "huge", "precious"]
  static var second = ["amaze", "energy", "non-living", "amusing", "enormous", "noticed", "analyze", "escape", "observed", "annoy", "estimate", "opinion", "arranged", "exercise", "peeking", "avoid", "expect", "plan", "cause", "famous", "poke", "classify", "flock", "predict", "community", "friendly", "prefer", "conclusion", "frighten", "process", "connection", "frown", "publish", "continue", "gasp", "records", "cooperation", "gather", "revise", "curious", "gust", "separate", "cycle", "helpful", "steaming", "data", "include", "shivered", "describe", "insist", "similar", "detail", "investigate", "sum", "diagram", "label", "suppose", "difference", "leaned", "sway", "different", "living", "stormy", "discover", "march", "swoop", "drowsy", "matter", "treasure", "edit", "moist", "vanish", "effect", "necessary", "volunteer"]
  static var third = ["additional", "event", "region", "agreeable", "examine", "repair", "argue", "example", "ridiculous", "arrange", "experience", "scar", "assist", "fatal", "scatter", "attract", "flexible", "shiver", "careless", "furious", "signal", "cause", "gathered", "similar", "climate", "gist", "slumber", "coast", "infer", "solution", "compare", "intelligent", "starve", "construct", "invitation", "stumble", "continent", "irritate", "tackle", "contrast", "marine", "tentacle", "credit", "mend", "typical", "culture", "multiply", "unite", "dangle", "nervous", "unusual", "defend", "occur", "valuable", "describe", "opposite", "vehicle", "details", "passage", "volunteer", "develop", "patient", "diagram", "peer", "disappointed", "persuade", "division", "pleasant", "effect", "prank", "elect", "predict", "purpose", "endangered", "recognize"]
  static var fourth = ["accomplish", "essential", "reason", "adaptation", "estimate", "recognize", "approached", "evidence", "recommend", "argued", "example", "represent", "automatically", "except", "result", "avoid", "exclaimed", "scarce", "border", "experiment", "select", "calculate", "flexible", "separate", "cause", "fortunate", "simplify", "circular", "frequent", "summarize", "compare", "furious", "surround", "concluding", "increasing", "support", "confirm", "infer", "temporary", "contrast", "inform", "threatens", "convince", "insert", "tradition", "critical", "maximum", "minimum", "decrease", "typical", "usually", "defend", "observe", "demonstrate", "organized", "describe", "obvious", "detail", "passage", "develop", "persuade", "difference", "predict", "prefer", "disappointed", "distribute", "previous", "effective", "purpose", "eliminate", "prediction", "rarely", "entirety"]
  static var fifth = ["abolish", "escalate", "influence", "accomplish", "establish", "investigate", "accurate", "evaluate", "navigate", "announce", "evidence", "opposed", "anxious", "exhaust", "ordinary", "approach", "expansion", "passage", "approval", "expectation", "persuade", "approximate", "explain", "primary", "argument", "express", "recently", "avoid", "extend", "reference", "briskly", "familiar", "review", "cease", "frequent", "revolt", "claim", "gigantic", "scarce", "conclude", "gist", "significant", "conflict", "glare", "source", "consistent", "harsh", "summarize", "context", "heroic", "superior", "convince", "hesitate", "tension", "culture", "hilarious", "tolerate", "decade", "historic", "tremble", "dissatisfied", "horizontal", "unexpected", "dominate", "hostile", "unfamiliar", "drowsy", "huddle", "vertical", "edible", "identify", "effortless", "illegible", "equivalent", "immigrate"]
  static var sixth = ["adjacent", "dimension", "obedient", "accumulate", "drastic", "oblivious", "adapt", "elaborate", "origin", "adequate", "encourage", "peculiar", "analyze", "equation", "persuade", "anticipate", "evaluate", "prediction", "appropriate", "exaggerate", "priority", "artifact", "exhaust", "quote", "benefit", "expression", "realistic", "calculate", "extend", "recount", "catastrophe", "extensive", "reinforce", "chronological", "factor", "repetition", "citizen", "ferocious", "retrieve", "civilization", "frequent", "frequency", "compose", "genuine", "solution", "conclusion", "government", "strategy", "congruent", "history", "substitute", "consequence", "hypothesis", "suspense", "construct", "insists", "tentative", "continuous", "irrigate", "thesis", "contrast", "lofty", "transfer", "contribute", "manipulate", "unanimous", "declare", "massive", "unique", "democracy", "narrate", "variable", "similar", "viewpoint", "violate"]
  static var seventh = ["abdicate", "connotation", "legendary", "abrasive", "consecutive", "liaison", "abruptly", "irrelevant", "libel", "acknowledge", "consult", "ludicrous", "acquire", "contrast", "mandatory", "addict", "copious", "mitigate", "adequate", "correspond", "naive", "admonish", "dawdle", "narrate", "affiliation", "deceitful", "necessity", "agitate", "demeanor", "negligent", "allege", "derogatory", "obnoxious", "allocate", "devastate", "omit", "alternative", "devious", "opposition", "amendment", "devour", "oppress", "antagonize", "diversity", "perceive", "attribute", "eligible", "persuasive", "authentic", "emphasize", "prediction", "bamboozle", "estimate", "prominent", "belligerent", "evaluate", "prospective", "bewilder", "bewildered", "exonerated", "punctual", "exposition", "quote", "bias", "exuberant", "relinquish", "boycott", "famished", "resolve", "condor", "formidable", "rudimentary", "cause", "impartial", "signify", "characterize", "indifferent", "sovereign", "chronological", "industrious", "suspense", "compel", "inevitable", "talisman", "competent", "infuriate", "tentative", "component", "inhabitants", "toxic", "conclusive", "initiate", "treason", "concur", "intimidate", "viewpoint", "condemn", "irate", "confront"]
  static var eighth = ["abhor", "construct", "precise", "abrasive", "contrast", "prediction", "alternative", "corroborate", "prevalent", "ambiguous", "depict", "procedure", "amiss", "derive", "profound", "anarchy", "despicable", "proprietor", "anonymous", "despondent", "prudent", "anthology", "elapse", "pseudonym", "apathy", "embark", "quote", "apprehend", "encompass", "rebel", "assimilate", "endeavor", "rebuff", "assumption", "evidence", "rebuke", "audacious", "evoke", "recur", "authority", "feasible", "resilient", "avid", "focus", "response", "ban", "formula", "reverberate", "belligerent", "generation", "significant", "bisect", "gruesome", "similar", "bizarre", "imminent", "simulate", "boycott", "impel", "simultaneous", "capable", "imperative", "source", "cause", "integrate", "specific", "characterize", "interrogate", "spontaneous", "chronological", "merge", "surmise", "commence", "modify", "theory", "compels", "mutiny", "tirade", "concise", "narrate", "universal", "conclude", "novice", "validate", "confiscate", "obsolete", "variable", "conjecture", "opposition", "conscientious", "perish", "consecutive", "perspective", "consistent", "persuasive", "inspire", "plagiarize"]
  static var LEVELS = [first, second, third, fourth, fifth, sixth, seventh, eighth]
}
